# Generated by Django 4.0.2 on 2022-02-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_book_name_alter_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='user', max_length=25),
        ),
    ]
