# Generated by Django 4.0.2 on 2022-02-20 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='images/221182406_998264654304104_3219754300096054984_n.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
