# Generated by Django 4.0.2 on 2022-02-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='num_stars',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bio',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
