# Generated by Django 4.0.2 on 2022-02-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_num_stars_book_rating_rename_bio_book_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Fiction', 'Fiction'), ('Classics', 'Classics'), ('Mystery', 'Mystery'), ('Comic', 'Comic'), ('Nonfiction', 'Nonfiction'), ('Fantasy', 'Fantasy')], default='None', max_length=200),
        ),
    ]
